# Apache Superset Helm Chart Values

# Image Configuration
image:
  repository: apache/superset
  tag: "latest"
  pullPolicy: IfNotPresent

# Postgres (AWS RDS) Configuration
postgres:
  enabled: false   
  externalDatabase:
    host: zinc-superset-dev.cosmcmqeobox.us-east-1.rds.amazonaws.com # RDS PostgreSQL endpoint
    port: 5432
    database: superset_db
    user: "{{ .Values.secrets.postgres_user }}"
    password: "{{ .Values.secrets.postgres_password }}"

# Redis (AWS ElastiCache) Configuration
redis:
  enabled: false   
  externalRedis:
    host: clustercfg.zinc-superset-dev-v1.ikhhqi.use1.cache.amazonaws.com:6379  # ElastiCache Redis endpoint
    port: 6379
    password: "{{ .Values.secrets.redis_password }}"

# Service Account Configuration for IAM Role Integration
serviceAccountName: superset-serviceaccount
serviceAccountAnnotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::621454496946:role/zinc-superset-eks-role  # Replace with your IAM role ARN

# Ingress Configuration (for AWS ALB)
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: "Internal"
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:region:account-id:certificate/certificate-id  # Optional
  hosts:
    - superset.zinc-app.com  # Replace with your domain name

# Horizontal Pod Autoscaler (HPA) Configuration
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Superuser Credentials (Can be configured from AWS Secrets Manager or provided here)
superuser:
  username: admin
  password: admin

# Secrets Configuration for Sensitive Data
secrets:
  postgres_user: "arn:aws:secretsmanager:us-east-1:621454496946:secret:zinc-superset-rds-secrets-19u8iK:postgres-user"
  postgres_password: "arn:aws:secretsmanager:us-east-1:621454496946:secret:zinc-superset-rds-secrets-19u8iK:postgres-password"
  redis_password: "arn:aws:secretsmanager:us-east-1:621454496946:secret:zinc-superset-dev-redis-secrets-1x1x3r"
  superset_secret_key: "arn:aws:secretsmanager:us-east-1:621454496946:secret:superset-secret-key-E4g2kY"
#  superset_superuser_username: "arn:aws:secretsmanager:us-east-1:621454496946:secret:zinc-superset-superuser-credentials-dev-y3QdGl:username"
#  superset_superuser_password: "arn:aws:secretsmanager:us-east-1:621454496946:secret:zinc-superset-superuser-credentials-dev-y3QdGl:password"