apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "superset.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/success-codes: 200,302
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:region:account-id:certificate/certificate-id  # Optional SSL
spec:
  ingressClassName: alb
  rules:
    - host: superset.zinc-app.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "superset.fullname" . }}
                port:
                  number: 8088