apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
type: Opaque
data:
  postgres_user: {{ .Values.secrets.postgres_user | b64enc }}
  postgres_password: {{ .Values.secrets.postgres_password | b64enc }}
  redis_password: {{ .Values.secrets.redis_password | b64enc }}
  superset_secret_key: {{ .Values.secrets.superset_secret_key | b64enc }}